
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  const { topic } = req.body;

  if (!topic || topic.trim() === '') {
    return res.status(400).json({ message: 'Topic is required' });
  }

  try {
    // Simulate AI content generation
    const article = `
      ## ${topic}
      In this article, we explore key insights about **${topic}**. Whether you're new to the topic or already familiar, this guide will offer fresh perspectives, practical advice, and motivational truths that will inspire your journey.

      ### Introduction
      Every great idea begins with a spark. ${topic} is one such spark that ignites change and transformation.

      ### Key Takeaways
      - Understand the essence of ${topic}
      - Apply core principles to real-life scenarios
      - Learn from case studies and examples

      ### Conclusion
      The power of ${topic} lies in its ability to shift your mindset and position you for results. Embrace it fully and watch your world change.

      *Article generated by CYBEV AI Assistant*
    `;

    return res.status(200).json({ article });
  } catch (error) {
    console.error('AI generation error:', error);
    return res.status(500).json({ message: 'Failed to generate article' });
  }
}
